import USDC from "./usdc.png"
import ETH from "./WETH.png"
import BTC from "./btc.png"
import SOLANA from "./solana.png"
import MATIC from "./matic.png"
import POLYGON from "./polygon.png"
import CAKE from "./CAKE.png"
import DOGE from "./dogecoin.png"
import PEPE from "./pepe.png"
export { USDC, ETH, BTC, SOLANA, MATIC, POLYGON, CAKE, DOGE, PEPE }
