import Rewards from "./rewards.png"
import OKX from "./okx.png"
import ChainLink from "./chainlink.svg"
import Binance from "./Binance.svg"
import Kucoin from "./kucoin.svg"
import Coinbase from "./coinbase.svg"
import Bybit from "./bybit.svg"
import Ethereum from "./Ethereum.svg"
import Bitcoin from "./Bitcoin.svg"
import USDC from "./USDC.svg"
export { Rewards, OKX, ChainLink, Binance, Kucoin, Coinbase, Bybit, Ethereum, Bitcoin, USDC }